[package]
name = "bls_binary_rust"
version = "0.0.1"
description = "BLS signature library for Ethereum 2.0"
license = "BSD-3-Clause OR MIT OR Apache-2.0"
edition = "2018"


[dependencies]
criterion = "0.3.0"
hex = "0.4.0"
rand = "0.7"
num_cpus = "1.13.0"
